name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - name: Install Python 3
            uses: actions/setup-python@v1
            with:
              python-version: 3.8
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip        
              pip install -r requirements.txt
              python3 setup.py build_ext --inplace
          - name: Run tests
            run: python3 -m unittest tests/ana_cont_tests.py -v
